# Generated by Django 6.0.2 on 2026-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
