# Generated by Django 6.0.2 on 2026-02-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
