# Generated by Django 6.0.2 on 2026-02-12 17:20

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for the article', null=True, upload_to=pathlib.PurePosixPath('/Users/radoslavraychev/PycharmProjects/Python-Web/Django-Basics/BalkanPress/media')),
        ),
    ]
