# Generated by Django 6.0.2 on 2026-02-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_featured_image"),
        ("tags", "0002_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a featured image for the article",
                null=True,
                upload_to="media/",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="tags.tag"
            ),
        ),
    ]
