# Generated by Django 6.0.2 on 2026-02-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_featured_image_alter_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a featured image for the article",
                null=True,
                upload_to=".",
            ),
        ),
    ]
