# Generated by Django 6.0.2 on 2026-03-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newslettersubscriber",
            name="updated_at",
        ),
    ]
